@startuml

package "应用层" {
    [查询天气]
    [获取城市信息]
    [获取账户信息]
    [查看笑话]
    [查看笑话详情]
}
package "网络层" {
    [网络接口]
    [网络请求]
}


package "百度服务" {
    [定位接口]
    [定位请求]
}

package "数据层" {
    [账户信息]
    [天气数据]
    [笑话信息]
    [笑话详情信息]
    [城市信息]
}


[获取城市信息] --> [定位接口]:请求
[查询天气] --> [网络接口]:请求
[查看笑话] --> [网络接口]:请求
[查看笑话详情] --> [网络接口]:请求
[获取账户信息] --> [网络接口]:请求

[网络接口] --> [网络请求]
[网络请求]..> HTTP:use
[网络请求] --> [服务端]:HTTP请求

[网络请求] --> [网络接口]

[查询天气] --> [天气数据]:解析数据
[查看笑话] --> [笑话信息]:解析数据
[查看笑话详情] --> [笑话详情信息]:解析数据
[获取账户信息] --> [账户信息]:解析数据

[定位接口] --> [定位请求]
[定位请求] --> [定位接口]
[获取城市信息] --> [城市信息]:解析数据

@enduml